/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_cameratest_liveness_LivenessDetection */

#ifndef _Included_com_example_cameratest_liveness_LivenessDetection
#define _Included_com_example_cameratest_liveness_LivenessDetection
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_cameratest_liveness_LivenessDetection
 * Method:    detectLiveness
 * Signature: ([I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_cameratest_liveness_LivenessDetection_detectLiveness
  (JNIEnv *, jclass, jintArray);

#ifdef __cplusplus
}
#endif
#endif
